version: "2"
services:
  test-postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
  test:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres@test-postgres/test
      ODATA_ENTITY_CONTAINER_KEY: ODataDemo
    links:
      - test-postgres
